version: '2'
services:
  web:
    image: java
    restart: always
    ports:
      - 8769:8769
      - 8766:8766
    container_name: socket-netty-test
    volumes:
      - /root/socketNettyDemo:/socketNettyDemo
    working_dir: /socketNettyDemo
    command: java -jar ./target/socket_netty_demo-0.0.1-SNAPSHOT.jar