server:
  port: 8769
logging:
  level:
    root:
      info
  file:
    path: ./logs
spring:
  rabbitmq:
    host: 120.27.232.182
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 120.27.232.182
    port: 6379
  data:
    mongodb:
      uri: mongodb://120.27.232.182:27017/oshop